# Generated by Django 5.2.7 on 2025-12-31 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20211130_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='recipes/covers/%Y/%m/%d/'),
        ),
    ]
